// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'FooterComponent': typeof import("../../components/FooterComponent.vue")['default'],
    'HeaderComponent': typeof import("../../components/HeaderComponent.vue")['default'],
    'MenuComponent': typeof import("../../components/MenuComponent.vue")['default'],
    'NuxtWelcome': typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../../node_modules/nuxt3/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'NuxtLink': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
    'LazyFooterComponent': typeof import("../../components/FooterComponent.vue")['default'],
    'LazyHeaderComponent': typeof import("../../components/HeaderComponent.vue")['default'],
    'LazyMenuComponent': typeof import("../../components/MenuComponent.vue")['default'],
    'LazyNuxtWelcome': typeof import("../../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../../node_modules/nuxt3/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../../node_modules/nuxt3/dist/app/components/client-only")['default'],
    'LazyNuxtLink': typeof import("../../node_modules/nuxt3/dist/app/components/nuxt-link")['default']
  }
}
export {}
